CREATE TABLE `annotations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fileId` int NOT NULL,
	`userId` int NOT NULL,
	`type` enum('highlight','underline','strikethrough','text','shape','stamp','signature','comment','drawing') NOT NULL,
	`pageNumber` int NOT NULL,
	`positionX` int NOT NULL,
	`positionY` int NOT NULL,
	`width` int,
	`height` int,
	`content` text,
	`color` varchar(32),
	`shapeType` varchar(32),
	`strokeWidth` int,
	`pathData` text,
	`isResolved` boolean DEFAULT false,
	`resolvedBy` int,
	`resolvedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `annotations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cost_tracking` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`teamId` int,
	`date` timestamp NOT NULL,
	`computeCost` decimal(10,4) NOT NULL DEFAULT '0',
	`storageCost` decimal(10,4) NOT NULL DEFAULT '0',
	`bandwidthCost` decimal(10,4) NOT NULL DEFAULT '0',
	`aiProcessingCost` decimal(10,4) NOT NULL DEFAULT '0',
	`totalCost` decimal(10,4) NOT NULL DEFAULT '0',
	`conversionsCount` int NOT NULL DEFAULT 0,
	`ocrPagesProcessed` int NOT NULL DEFAULT 0,
	`transcriptionMinutes` int NOT NULL DEFAULT 0,
	`aiChatTokens` int NOT NULL DEFAULT 0,
	`storageGbHours` decimal(10,4) NOT NULL DEFAULT '0',
	`bandwidthGb` decimal(10,4) NOT NULL DEFAULT '0',
	`subscriptionRevenue` decimal(10,4) NOT NULL DEFAULT '0',
	`adRevenue` decimal(10,4) NOT NULL DEFAULT '0',
	`totalRevenue` decimal(10,4) NOT NULL DEFAULT '0',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `cost_tracking_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `pdf_comparisons` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`file1Id` int NOT NULL,
	`file2Id` int NOT NULL,
	`totalPages` int NOT NULL,
	`changedPages` int NOT NULL,
	`addedPages` int NOT NULL DEFAULT 0,
	`removedPages` int NOT NULL DEFAULT 0,
	`textAdditions` int NOT NULL DEFAULT 0,
	`textDeletions` int NOT NULL DEFAULT 0,
	`textModifications` int NOT NULL DEFAULT 0,
	`resultFileUrl` text,
	`diffDataJson` json,
	`status` enum('pending','processing','completed','failed') NOT NULL DEFAULT 'pending',
	`errorMessage` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	CONSTRAINT `pdf_comparisons_id` PRIMARY KEY(`id`)
);
