import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

import 'locales/ar.dart';
import 'locales/bn.dart';
import 'locales/cs.dart';
import 'locales/da.dart';
import 'locales/de.dart';
import 'locales/el.dart';
import 'locales/en.dart';
import 'locales/es.dart';
import 'locales/fi.dart';
import 'locales/fr.dart';
import 'locales/gu.dart';
import 'locales/he.dart';
import 'locales/hi.dart';
import 'locales/hu.dart';
import 'locales/id.dart';
import 'locales/it.dart';
import 'locales/ja.dart';
import 'locales/ko.dart';
import 'locales/mr.dart';
import 'locales/ms.dart';
import 'locales/nl.dart';
import 'locales/no.dart';
import 'locales/pl.dart';
import 'locales/pt.dart';
import 'locales/ro.dart';
import 'locales/ru.dart';
import 'locales/sv.dart';
import 'locales/sw.dart';
import 'locales/ta.dart';
import 'locales/te.dart';
import 'locales/th.dart';
import 'locales/tl.dart';
import 'locales/tr.dart';
import 'locales/uk.dart';
import 'locales/vi.dart';
import 'locales/zh.dart';

/// Resolves a string for a localization key.
///
/// Looks up the value in the locale-specific map. If the key is missing
/// from that locale (or the locale itself isn't registered), falls back to
/// English. If the key isn't in English either, returns the key verbatim
/// so the missing-translation is visible in the UI.
String _resolve(Locale locale, String key) {
  final map = _localizedValues[locale.languageCode];
  final value = map?[key];
  if (value != null) return value;
  final en = _localizedValues['en']?[key];
  if (en != null) return en;
  return key;
}

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const List<LocalizationsDelegate<dynamic>> localizationsDelegates = [
    delegate,
    GlobalMaterialLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
  ];

  /// 36 locales, one per file under `locales/`.
  /// Keep this list in sync with `LOCALES` in
  /// `scripts/locale_data.py` and the locale file imports above.
  static const List<Locale> supportedLocales = [
    Locale('en'), // English
    Locale('es'), // Spanish
    Locale('fr'), // French
    Locale('de'), // German
    Locale('it'), // Italian
    Locale('pt'), // Portuguese
    Locale('ru'), // Russian
    Locale('zh'), // Chinese
    Locale('ja'), // Japanese
    Locale('ko'), // Korean
    Locale('ar'), // Arabic
    Locale('hi'), // Hindi
    Locale('th'), // Thai
    Locale('vi'), // Vietnamese
    Locale('pl'), // Polish
    Locale('tr'), // Turkish
    Locale('nl'), // Dutch
    Locale('sv'), // Swedish
    Locale('no'), // Norwegian
    Locale('da'), // Danish
    Locale('fi'), // Finnish
    Locale('cs'), // Czech
    Locale('hu'), // Hungarian
    Locale('ro'), // Romanian
    Locale('uk'), // Ukrainian
    Locale('he'), // Hebrew
    Locale('el'), // Greek
    Locale('bn'), // Bengali
    Locale('id'), // Indonesian
    Locale('ms'), // Malay
    Locale('tl'), // Filipino / Tagalog
    Locale('sw'), // Swahili
    Locale('ta'), // Tamil
    Locale('te'), // Telugu
    Locale('mr'), // Marathi
    Locale('gu'), // Gujarati
  ];

  /// Per-locale map registry. Each map is auto-generated by
  /// `scripts/generate_locales.py` from `scripts/locale_data.py`.
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': localeEn,
    'es': localeEs,
    'fr': localeFr,
    'de': localeDe,
    'it': localeIt,
    'pt': localePt,
    'ru': localeRu,
    'zh': localeZh,
    'ja': localeJa,
    'ko': localeKo,
    'ar': localeAr,
    'hi': localeHi,
    'th': localeTh,
    'vi': localeVi,
    'pl': localePl,
    'tr': localeTr,
    'nl': localeNl,
    'sv': localeSv,
    'no': localeNo,
    'da': localeDa,
    'fi': localeFi,
    'cs': localeCs,
    'hu': localeHu,
    'ro': localeRo,
    'uk': localeUk,
    'he': localeHe,
    'el': localeEl,
    'bn': localeBn,
    'id': localeId,
    'ms': localeMs,
    'tl': localeTl,
    'sw': localeSw,
    'ta': localeTa,
    'te': localeTe,
    'mr': localeMr,
    'gu': localeGu,
  };

  String getString(String key) => _resolve(locale, key);
  String get(String key) => getString(key);
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales
        .any((l) => l.languageCode == locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
