#!/usr/bin/env python3
"""Generate 36 Dart locale files for ProPDFs.

Each locale gets its own file under frontend/lib/core/localization/locales/.
The keys for every locale MUST be identical to the English source of truth.
Any missing key in a non-English file falls back to English at runtime via
AppLocalizations.get.

Run from the repo root:
    python3 scripts/generate_locales.py
"""
from pathlib import Path

OUT = Path("frontend/lib/core/localization/locales")
OUT.mkdir(parents=True, exist_ok=True)


def _emit(lang_code: str, class_name: str, items: dict[str, str]) -> Path:
    """Write one .dart file with `const Map<String, String> <name> = {...};`."""
    lines = [
        "// AUTO-GENERATED by scripts/generate_locales.py — do not edit by hand.",
        "// To update, edit the generator and re-run it.",
        f"// Locale: {lang_code}",
        "",
        f"const Map<String, String> locale{class_name} = {{",
    ]
    for k, v in items.items():
        # Escape Dart string literals
        escaped = v.replace("\\", "\\\\").replace("'", "\\'").replace("$", "\\$")
        lines.append(f"  '{k}': '{escaped}',")
    lines.append("};")
    lines.append("")  # trailing newline
    path = OUT / f"{lang_code}.dart"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def write_all(locales: dict[str, tuple[str, dict[str, str]]]) -> list[Path]:
    """Write all locale files. locales[code] = (PascalCaseName, dict)."""
    written: list[Path] = []
    for code, (name, items) in locales.items():
        written.append(_emit(code, name, items))
    return written
